baseURL = 'https://nomadmotors.github.io/'
languageCode = 'en-us'
title = 'Nomad Development Blog'
theme = ['etch', 'hugo-video']
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
disablePathToLower = true

[params]
  description = "Nomad Development Blog"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  unsafe = true